### Diferença entre Tipos Dinâmicos e Arrays de Tipo Fixo

Observe a diferença aqui: um inteiro em C é basicamente um rótulo para uma posição na memória que armazena o valor inteiro diretamente. Já um inteiro em Python é um ponteiro para uma posição na memória que contém todas as informações do objeto Python, incluindo o valor inteiro. Essas informações extras permitem que Python seja tão flexível e dinâmico, mas também têm um custo. Isso se torna evidente em estruturas que combinam muitos desses objetos.

Essa flexibilidade vem com um preço: para permitir tipos variados, cada item na lista deve conter suas próprias informações de tipo, contagem de referência e outras informações — ou seja, cada item é um objeto Python completo. Quando todas as variáveis são do mesmo tipo, muitas dessas informações são redundantes, e é muito mais eficiente armazenar dados em um array de tipo fixo. A diferença entre uma lista de tipo dinâmico e um array de tipo fixo (como em NumPy) é mostrada na figura a seguir:

![Diferença entre Lista Dinâmica e Array de Tipo Fixo](https://raw.githubusercontent.com/naticost/DataAnalytics/main/Python/img/array_vs_list.png)


In [39]:
import numpy as np


In [7]:
# matriz de inteiros: 
np.array([1, 4, 2, 5, 6])

array([1, 4, 2, 5, 3])

## NumPy é restrito a arrays que contêm todos o mesmo tipo. Se os tipos não corresponderem, o NumPy fará upcast se possível (aqui, inteiros são upcast para ponto flutuante)

In [16]:
np . array ([ 3.14 ,  4 ,  2 ,  5 ])


array([3.14, 4.  , 2.  , 5.  ])

In [11]:
np.array([1, 2, 3, 4], dtype='float32') #Float de precisão simples: bit de sinal, expoente de 8 bits, mantissa de 23 bits


array([1., 2., 3., 4.], dtype=float32)

In [12]:
# listas aninhadas resultam em matrizes multidimensionais 
np.array([range(i, i + 2) for i in [2, 4, 5]])

array([[2, 3],
       [4, 5],
       [5, 6]])

### Criando matrizes do zero

In [17]:
# Crie uma matriz de inteiros de comprimento 10 preenchida com zeros 
np . zeros ( 10 ,  dtype = int )


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Crie uma matriz de ponto flutuante 3x5 preenchida com uns 
np . ones (( 3 ,  5 ),  dtype = float )

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Crie uma matriz 3x5 preenchida com 3,14 
np . full (( 3 ,  5 ),  3.14 )

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
# Crie uma matriz preenchida com uma sequência linear 
# Começando em 0, terminando em 20, avançando de 2 em 2 
# (isso é semelhante à função range() interna) 
np . arange ( 0 ,  20 ,  2 )

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# Crie uma matriz de cinco valores uniformemente espaçados entre 0 e 1 
np . linspace ( 0 ,  1 ,  5 )

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Crie uma matriz 3x3 de valores aleatórios uniformemente distribuídos entre 0 e 1 
np.random.random((3, 3))


array([[0.00144818, 0.26933413, 0.18675059],
       [0.83284662, 0.40251494, 0.58966754],
       [0.38071478, 0.303591  , 0.02941909]])

In [23]:
# Crie uma matriz 3x3 de valores aleatórios distribuídos normalmente com média 0 e desvio padrão 1
np.random.normal(0, 1, (3, 3))


array([[-1.97094109, -0.93940411,  0.93365982],
       [-0.22865561, -0.21793498,  0.29018885],
       [-1.30663809, -1.51924742, -1.09521413]])

In [24]:
# Crie uma matriz 3x3 de inteiros aleatórios no intervalo [0, 10) 
np.random.randint(0, 10, (3, 3))



array([[0, 6, 1],
       [9, 5, 4],
       [2, 7, 5]])

In [25]:
# Crie uma matriz identidade 3x3 
np.eye(3)



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# Crie uma matriz não inicializada de três inteiros 
# Os valores serão o que já existir naquele local de memória 
np.empty(3)


array([1., 1., 1.])

## Atributos de matriz NumPy 

In [27]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [28]:
print("x3 ndim: ", x3.ndim) #número de dimensão
print("x3 shape:", x3.shape) #tamanho de cada dimensão
print("x3 size: ", x3.size) #tamanho total da matriz


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


## Indexação de matriz: acessando elementos individuais 

In [29]:
x1


array([5, 0, 3, 3, 7, 9])

In [30]:
x1 [ 0 ]


5

In [31]:
x1 [ 4 ]


7

In [32]:
x1 [ - 1 ]


9

In [33]:
x1 [ - 2 ]


7

In [34]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2 [ 0 ,  0 ]


3

In [36]:
x2 [ 0 ,  0 ]  =  12 
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Fatiamento de matrizes: acessando submatrizes 

x [ início : fim : passo ]

start=0, stop=size of dimension, step=1


In [41]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[:5]  # primeiros cinco elementos


array([0, 1, 2, 3, 4])

In [43]:
x[5:]   # elementos após o índice 5


array([5, 6, 7, 8, 9])

In [55]:
x[4:7]   # submatriz do meio


array([4, 5, 6])

In [45]:
x[::2]  # todos os outros elementos


array([0, 2, 4, 6, 8])

In [46]:
x[1::2]  # todos os outros elementos, começando no índice 1


array([1, 3, 5, 7, 9])

In [47]:
x [:: - 1 ]   # todos os elementos, invertidos


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x [ 5 :: - 2 ]   # invertido todos os outros a partir do índice 5


array([5, 3, 1])

## Submatrizes multidimensionais 

In [49]:
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [50]:
x2 [: 2 ,  : 3 ]   # duas linhas, três colunas


array([[12,  5,  2],
       [ 7,  6,  8]])

In [51]:
x2 [: 3 ,  :: 2 ]   # todas as linhas, todas as outras colunas


array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [52]:
x2 [:: - 1 ,  :: - 1 ]


array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [56]:
print ( x2 [:,  0 ])   # primeira coluna de x2


[12  7  1]


In [57]:
print ( x2 [ 0 ,  :])   # primeira linha de x2


[12  5  2  4]


## Subarrays como visualizações sem cópia

In [59]:
print ( x2 )


[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [60]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [61]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [62]:
print(x2)


[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Criando cópias de matrizes

In [63]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [64]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [65]:
print(x2)


[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Remodelagem de matrizes 

In [66]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.array([1, 2, 3])

# vetor linha via remodelação 
x.reshape((1, 3))

array([[1, 2, 3]])

In [68]:
# vetor linha via newaxis 
x[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
# vetor de coluna via remodelar 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [70]:
# vetor de coluna via newaxis 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenação e divisão de matrizes

In [71]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [72]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [73]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [74]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
np.concatenate([grid, grid], axis=1)
# concatenar ao longo do segundo eixo (indexado a zero) 



array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# empilhar verticalmente os arrays 
np.vstack([x, grid])

# Para trabalhar com matrizes de dimensões mistas, pode ser mais claro usar as funções np.vstack(pilha vertical) e np.hstack(pilha horizontal)


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [77]:
# empilhar horizontalmente os arrays 
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Divisão de matrizes

In [78]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [79]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [81]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Funções trigonométricas

In [83]:
theta = np.linspace(0, np.pi, 3)


In [84]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [85]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## Expoentes e logaritmos

In [86]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [87]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [88]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


## Summing the Values in an Array

In [89]:
import numpy as np


In [90]:
L = np.random.random(100)
sum(L)

52.12818058833704

In [91]:
np.sum(L)


52.12818058833702

In [92]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

The slowest run took 4.01 times longer than the fastest. This could mean that an intermediate result is being cached.
164 ms ± 111 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.04 ms ± 571 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Minimum and Maximum

In [93]:
min(big_array), max(big_array)


(1.4057692298008462e-06, 0.9999994392723005)

In [94]:
np.min(big_array), np.max(big_array)


(1.4057692298008462e-06, 0.9999994392723005)

In [95]:
%timeit min(big_array)
%timeit np.min(big_array)

116 ms ± 36.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.07 ms ± 101 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [96]:
print(big_array.min(), big_array.max(), big_array.sum())


1.4057692298008462e-06 0.9999994392723005 500202.5348847683


## Multi dimensional aggregates

In [97]:
M = np.random.random((3, 4))
print(M)


[[0.50063048 0.07383653 0.49018646 0.72521956]
 [0.84926562 0.10226215 0.99559424 0.59250301]
 [0.53509    0.88518089 0.25518136 0.13130483]]


In [98]:
M.sum()


6.1362551272647154

In [99]:
M.min(axis=0)


array([0.50063048, 0.07383653, 0.25518136, 0.13130483])

In [100]:
M.max(axis=1)


array([0.72521956, 0.99559424, 0.88518089])

In [1]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b
a + 5



array([5, 6, 7])

In [2]:
M = np.ones((3, 3))
print(M)
M + a


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

a + b


[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [3]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [4]:
[x[3], x[7], x[2]]


[71, 86, 14]

In [5]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [6]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [7]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Regras de transmissão em NumPy:

### Regra 1: Preenchimento com unidades

Se as duas matrizes tiverem um número diferente de dimensões, a matriz com menos dimensões será preenchida com unidades no lado esquerdo.

In [1]:
import numpy as np

# Matriz A com 2 dimensões
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matriz B com 1 dimensão
B = np.array([1, 2, 3])

# A forma de B será preenchida com unidades no lado esquerdo para igualar a de A
# A: (2, 3)
# B: (1, 3) -> (1, 3)

# Resultado da transmissão
C = A + B
print(C)


[[2 4 6]
 [5 7 9]]


### Regra 2: Esticamento de unidades


Se as formas das duas matrizes não corresponderem em nenhuma dimensão, a matriz com forma igual a 1 naquela dimensão será esticada para corresponder ao outro formato.

In [ ]:
import numpy as np

# Matriz A com forma (2, 3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matriz B com forma (2, 1)
B = np.array([
    [10],
    [20]
])

# A forma de B será esticada para corresponder a A
# A: (2, 3)
# B: (2, 1) -> (2, 3)

# Resultado da transmissão
C = A + B
print(C)


### Regra 3: Erro em tamanhos incompatíveis

Se em qualquer dimensão os tamanhos forem diferentes e nenhum for igual a 1, um erro será gerado.


In [2]:
import numpy as np

# Matriz A com forma (2, 3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matriz B com forma (2, 2)
B = np.array([
    [10, 20],
    [30, 40]
])

# As formas não são compatíveis para transmissão
# A: (2, 3)
# B: (2, 2)

# Isso resultará em um erro
try:
    C = A + B
except ValueError as e:
    print(e)


operands could not be broadcast together with shapes (2,3) (2,2) 


# Np.Newaxis

é um objeto em NumPy que permite adicionar uma nova dimensão a um array, expandindo sua forma. Isso é especialmente útil em operações de transmissão (broadcasting), onde pode ser necessário ajustar as dimensões de um array para que ele seja compatível com outro array.

In [3]:
import numpy as np

# Vetor linha
a = np.array([1, 2, 3])

# Usando np.newaxis para transformar em vetor coluna
a_coluna = a[:, np.newaxis]

print("Vetor original (linha):")
print(a)
print("Forma:", a.shape)

print("\nVetor transformado (coluna):")
print(a_coluna)
print("Forma:", a_coluna.shape)


Vetor original (linha):
[1 2 3]
Forma: (3,)

Vetor transformado (coluna):
[[1]
 [2]
 [3]]
Forma: (3, 1)


### Comparações, Máscaras e Lógica Booleana
AND e OR executa uma única avaliação Booleana em um objeto inteiro, enquanto & e |executa múltiplas avaliações Booleanas no conteúdo (os bits ou bytes individuais) de um objeto. Para matrizes Booleanas NumPy, a última é quase sempre a operação desejada.

![Operadores equivalentes](https://raw.githubusercontent.com/naticost/DataAnalytics/main/Python/img/Operador_equivalente.png)

![Operadores equivalentes](https://raw.githubusercontent.com/naticost/DataAnalytics/main/Python/img/ufuncs_equi.png)

### Explorando a indexação sofisticada 

 significa passar um array de índices para acessar múltiplos elementos do array de uma vez. Por exemplo, considere o seguinte array:

In [4]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[x[3], x[7], x[2]]


[51 92 14 71 60 20 82 86 74 74]


[71, 86, 14]

In [7]:
ind = [3, 7, 4]
# podemos passar uma única lista ou array de índices para obter o mesmo resultado
x[ind]
#Ao usar indexação sofisticada, o formato do resultado reflete o formato das matrizes de índice em vez do formato da matriz que está sendo indexada
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Classificação rápida em NumPy: np.sorte ---  np.argsor

A função np.sort retorna uma cópia do array fornecido com os elementos ordenados. Esta função pode ordenar arrays em uma ou várias dimensões.

In [8]:
import numpy as np

# Criando um array unidimensional
arr = np.array([3, 1, 2, 5, 4])

# Ordenando o array
sorted_arr = np.sort(arr)

print("Array original:", arr)
print("Array ordenado:", sorted_arr)


Array original: [3 1 2 5 4]
Array ordenado: [1 2 3 4 5]


Para arrays multidimensionais, você pode especificar o eixo (axis) ao longo do qual deseja ordenar os elementos.

In [9]:
# Criando um array bidimensional
arr_2d = np.array([[3, 1, 2], [5, 4, 6]])

# Ordenando o array ao longo do eixo 0 (linhas)
sorted_arr_2d = np.sort(arr_2d, axis=0)

print("Array bidimensional original:\n", arr_2d)
print("Array bidimensional ordenado ao longo do eixo 0:\n", sorted_arr_2d)


Array bidimensional original:
 [[3 1 2]
 [5 4 6]]
Array bidimensional ordenado ao longo do eixo 0:
 [[3 1 2]
 [5 4 6]]


A função np.argsort retorna os índices que ordenariam um array. Em vez de retornar o array ordenado, ele retorna um array de índices que podem ser usados para obter o array ordenado.

In [10]:
import numpy as np

# Criando um array unidimensional
arr = np.array([3, 1, 2, 5, 4])

# Obtendo os índices que ordenariam o array
indices = np.argsort(arr)

print("Array original:", arr)
print("Índices para ordenação:", indices)

# Usando os índices para obter o array ordenado
sorted_arr = arr[indices]
print("Array ordenado usando np.argsort:", sorted_arr)


Array original: [3 1 2 5 4]
Índices para ordenação: [1 2 0 4 3]
Array ordenado usando np.argsort: [1 2 3 4 5]


In [11]:
# Criando um array bidimensional
arr_2d = np.array([[3, 1, 2], [5, 4, 6]])

# Obtendo os índices que ordenariam o array ao longo do eixo 0 (linhas)
indices_2d = np.argsort(arr_2d, axis=0)

print("Array bidimensional original:\n", arr_2d)
print("Índices para ordenação ao longo do eixo 0:\n", indices_2d)

# Usando os índices para obter o array ordenado ao longo do eixo 0
sorted_arr_2d = np.take_along_axis(arr_2d, indices_2d, axis=0)
print("Array bidimensional ordenado usando np.argsort ao longo do eixo 0:\n", sorted_arr_2d)


Array bidimensional original:
 [[3 1 2]
 [5 4 6]]
Índices para ordenação ao longo do eixo 0:
 [[0 0 0]
 [1 1 1]]
Array bidimensional ordenado usando np.argsort ao longo do eixo 0:
 [[3 1 2]
 [5 4 6]]


In [12]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


O primeiro elemento desse resultado fornece o índice do menor elemento, o segundo valor fornece o índice do segundo menor, e assim por diante. Esses índices podem então ser usados ​​(por meio de indexação sofisticada) para construir o array ordenado, se desejado:

In [13]:
x[i]


array([1, 2, 3, 4, 5])

### Classificando ao longo de linhas ou colunas

Um recurso útil dos algoritmos de classificação do NumPy é a capacidade de classificar ao longo de linhas ou colunas específicas de uma matriz multidimensional usando o axisargumento

In [15]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [16]:
# classificar cada coluna de X 
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [17]:
# classificar cada linha de X 
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Classificações Parciais: Particionamento

Às vezes, não estamos interessados em classificar o array inteiro, mas apenas em encontrar os k menores valores no array. Para isso, o NumPy fornece a função np.partition. A np.partition recebe um array e um número K; o resultado é um novo array onde os menores K valores estão à esquerda da partição, e os valores restantes à direita.

In [18]:
import numpy as np

# Criando um array
arr = np.array([7, 2, 5, 3, 9, 1, 8])

# Particionando o array para encontrar os 3 menores valores
k = 3
partitioned_arr = np.partition(arr, k)

print("Array original:", arr)
print(f"Array particionado com os {k} menores valores à esquerda:", partitioned_arr)


Array original: [7 2 5 3 9 1 8]
Array particionado com os 3 menores valores à esquerda: [1 2 3 5 7 9 8]
