### Diferença entre Tipos Dinâmicos e Arrays de Tipo Fixo

Observe a diferença aqui: um inteiro em C é basicamente um rótulo para uma posição na memória que armazena o valor inteiro diretamente. Já um inteiro em Python é um ponteiro para uma posição na memória que contém todas as informações do objeto Python, incluindo o valor inteiro. Essas informações extras permitem que Python seja tão flexível e dinâmico, mas também têm um custo. Isso se torna evidente em estruturas que combinam muitos desses objetos.

Essa flexibilidade vem com um preço: para permitir tipos variados, cada item na lista deve conter suas próprias informações de tipo, contagem de referência e outras informações — ou seja, cada item é um objeto Python completo. Quando todas as variáveis são do mesmo tipo, muitas dessas informações são redundantes, e é muito mais eficiente armazenar dados em um array de tipo fixo. A diferença entre uma lista de tipo dinâmico e um array de tipo fixo (como em NumPy) é mostrada na figura a seguir:

![Diferença entre Lista Dinâmica e Array de Tipo Fixo](https://raw.githubusercontent.com/naticost/DataAnalytics/main/Python/img/array_vs_list.png)


In [39]:
import numpy as np


In [7]:
# matriz de inteiros: 
np.array([1, 4, 2, 5, 6])

array([1, 4, 2, 5, 3])

## NumPy é restrito a arrays que contêm todos o mesmo tipo. Se os tipos não corresponderem, o NumPy fará upcast se possível (aqui, inteiros são upcast para ponto flutuante)

In [16]:
np . array ([ 3.14 ,  4 ,  2 ,  5 ])


array([3.14, 4.  , 2.  , 5.  ])

In [11]:
np.array([1, 2, 3, 4], dtype='float32') #Float de precisão simples: bit de sinal, expoente de 8 bits, mantissa de 23 bits


array([1., 2., 3., 4.], dtype=float32)

In [12]:
# listas aninhadas resultam em matrizes multidimensionais 
np.array([range(i, i + 2) for i in [2, 4, 5]])

array([[2, 3],
       [4, 5],
       [5, 6]])

### Criando matrizes do zero

In [17]:
# Crie uma matriz de inteiros de comprimento 10 preenchida com zeros 
np . zeros ( 10 ,  dtype = int )


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Crie uma matriz de ponto flutuante 3x5 preenchida com uns 
np . ones (( 3 ,  5 ),  dtype = float )

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Crie uma matriz 3x5 preenchida com 3,14 
np . full (( 3 ,  5 ),  3.14 )

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
# Crie uma matriz preenchida com uma sequência linear 
# Começando em 0, terminando em 20, avançando de 2 em 2 
# (isso é semelhante à função range() interna) 
np . arange ( 0 ,  20 ,  2 )

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# Crie uma matriz de cinco valores uniformemente espaçados entre 0 e 1 
np . linspace ( 0 ,  1 ,  5 )

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Crie uma matriz 3x3 de valores aleatórios uniformemente distribuídos entre 0 e 1 
np.random.random((3, 3))


array([[0.00144818, 0.26933413, 0.18675059],
       [0.83284662, 0.40251494, 0.58966754],
       [0.38071478, 0.303591  , 0.02941909]])

In [23]:
# Crie uma matriz 3x3 de valores aleatórios distribuídos normalmente com média 0 e desvio padrão 1
np.random.normal(0, 1, (3, 3))


array([[-1.97094109, -0.93940411,  0.93365982],
       [-0.22865561, -0.21793498,  0.29018885],
       [-1.30663809, -1.51924742, -1.09521413]])

In [24]:
# Crie uma matriz 3x3 de inteiros aleatórios no intervalo [0, 10) 
np.random.randint(0, 10, (3, 3))



array([[0, 6, 1],
       [9, 5, 4],
       [2, 7, 5]])

In [25]:
# Crie uma matriz identidade 3x3 
np.eye(3)



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# Crie uma matriz não inicializada de três inteiros 
# Os valores serão o que já existir naquele local de memória 
np.empty(3)


array([1., 1., 1.])

## Atributos de matriz NumPy 

In [27]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [28]:
print("x3 ndim: ", x3.ndim) #número de dimensão
print("x3 shape:", x3.shape) #tamanho de cada dimensão
print("x3 size: ", x3.size) #tamanho total da matriz


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


## Indexação de matriz: acessando elementos individuais 

In [29]:
x1


array([5, 0, 3, 3, 7, 9])

In [30]:
x1 [ 0 ]


5

In [31]:
x1 [ 4 ]


7

In [32]:
x1 [ - 1 ]


9

In [33]:
x1 [ - 2 ]


7

In [34]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2 [ 0 ,  0 ]


3

In [36]:
x2 [ 0 ,  0 ]  =  12 
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Fatiamento de matrizes: acessando submatrizes 

x [ início : fim : passo ]

start=0, stop=size of dimension, step=1


In [41]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[:5]  # primeiros cinco elementos


array([0, 1, 2, 3, 4])

In [43]:
x[5:]   # elementos após o índice 5


array([5, 6, 7, 8, 9])

In [55]:
x[4:7]   # submatriz do meio


array([4, 5, 6])

In [45]:
x[::2]  # todos os outros elementos


array([0, 2, 4, 6, 8])

In [46]:
x[1::2]  # todos os outros elementos, começando no índice 1


array([1, 3, 5, 7, 9])

In [47]:
x [:: - 1 ]   # todos os elementos, invertidos


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x [ 5 :: - 2 ]   # invertido todos os outros a partir do índice 5


array([5, 3, 1])

## Submatrizes multidimensionais 

In [49]:
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [50]:
x2 [: 2 ,  : 3 ]   # duas linhas, três colunas


array([[12,  5,  2],
       [ 7,  6,  8]])

In [51]:
x2 [: 3 ,  :: 2 ]   # todas as linhas, todas as outras colunas


array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [52]:
x2 [:: - 1 ,  :: - 1 ]


array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [56]:
print ( x2 [:,  0 ])   # primeira coluna de x2


[12  7  1]


In [57]:
print ( x2 [ 0 ,  :])   # primeira linha de x2


[12  5  2  4]


## Subarrays como visualizações sem cópia

In [59]:
print ( x2 )


[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [60]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [61]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [62]:
print(x2)


[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Criando cópias de matrizes

In [63]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [64]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [65]:
print(x2)


[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Remodelagem de matrizes 

In [66]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.array([1, 2, 3])

# vetor linha via remodelação 
x.reshape((1, 3))

array([[1, 2, 3]])

In [68]:
# vetor linha via newaxis 
x[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
# vetor de coluna via remodelar 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [70]:
# vetor de coluna via newaxis 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenação e divisão de matrizes

In [71]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [72]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [73]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [74]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
np.concatenate([grid, grid], axis=1)
# concatenar ao longo do segundo eixo (indexado a zero) 



array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# empilhar verticalmente os arrays 
np.vstack([x, grid])

# Para trabalhar com matrizes de dimensões mistas, pode ser mais claro usar as funções np.vstack(pilha vertical) e np.hstack(pilha horizontal)


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [77]:
# empilhar horizontalmente os arrays 
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Divisão de matrizes

In [78]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [79]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [81]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
