# Importação e Criação de Arrays 

### Importe a biblioteca Numpy.
### Crie um array de zeros com a forma (5, 5).
### Crie um array de uns com a forma (3, 2).
### Crie um array a partir de uma lista: [10, 20, 30, 40, 50].


In [13]:
import numpy as np

In [28]:
arry = np.zeros ((5,5))
arry

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arry = np.ones((3,2))
arry

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
lista = [10, 20, 30, 40, 50]

array = np.array(lista)
array

array([10, 20, 30, 40, 50])

# Manipulação de Arrays

### Crie um array 2D de números inteiros de 1 a 9 com a forma (3, 3).

### Acesse o elemento na segunda linha e terceira coluna.
### Extraia a primeira coluna do array.
### Modifique o valor do elemento na terceira linha e segunda coluna para 100.

In [32]:
arry = np.arange(1,10)
arry2d = arry.reshape((3,3))

print(arry2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
acessandoValor=arry2d[1,2]
print(acessandoValor)

6


In [38]:
extraindo = arry2d[:,0]
print(extraindo)

[1 4 7]


In [44]:
modificando = arry2d[2,1]=100
arry2d

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9]])

# Atributos e Métodos

### Crie um array de números de 0 a 15 com a forma (4, 4).


### Use o método .shape para obter as dimensões do array.

### Utilize o método .flatten() para converter o array em uma dimensão.

### Utilize o método .reshape() para mudar a forma do array para (2, 8).


# Indexação e Slicing


### Crie um array 1D de números de 10 a 50.

### Acesse o elemento no índice 5.

### Extraia os elementos do índice 3 ao 7.

### Crie um array 2D de números de 1 a 16 com a forma (4, 4).

### Extraia os elementos da segunda linha.

### Extraia a terceira coluna.

# Concatenando Arrays


### Crie dois arrays 2D: array1 com a forma (2, 2) e array2 com a forma (2, 2) e valores à sua escolha.

### Concatenar array1 e array2 ao longo do eixo 0.

### Crie dois arrays 2D: array3 com a forma (2, 2) e array4 com a forma (2, 1).

### Concatenar array3 e array4 ao longo do eixo 1.